### PR TITLE
use `hydra_plugins` namespace package

### PR DESCRIPTION
**Pull request by Jasha10**
See my comment [here](https://github.com/facebookresearch/hydra/issues/1943#issuecomment-1015852961)

The key change is to create a namespace package `hydra_plugins` with module `hydra_plugins/jz_hydra_submitit_launcher_plugin` inside of it. Using the name `hydra_plugins` allows hydra to discover the package. Thus the SearchPathPlugin is active, and it is no-longer necessary to specify `hydra.searchpath` in `jz_hydra_submitit_launcher/bin/hydra-submitit-launch`.

Note that `hydra_plugins` should be a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), i.e. `hydra_plugins/__init__.py` should not exist.

### CODE REVIEW

**Comment by zaccharieramzi** [comment]
This makes a lot of sense, thank you so much.

I am not sure I understand why there is no need to also move the different configurations under the `hydra_plugins` namespace package. Could you develop?

In any case I think it would be better to have it all in the same directory, if you don't mind changing it.
If you do, don't forget to change the path to the script: https://github.com/Jasha10/jz-hydra-submitit-launcher/blob/use_namespace_package/setup.py#L34

**Comment by Jasha10** [comment]
> I am not sure I understand why there is no need to also move the different configurations under the `hydra_plugins` namespace package. Could you develop?

Hydra's plugin discovery process is indepedent of it's config discovery process.
- The [plugin discovery process relies](https://hydra.cc/docs/advanced/plugins/develop/#plugin-discovery-process) on the the `hydra_plugins` namespace package. This is how the file `hydra_plugins/jz_hydra_submitit_launcher_plugin/searchpath_config.py` gets discovered and loaded.
- The config discovery process relies on a ["config search path"](https://hydra.cc/docs/advanced/search_path/), which is essentially a list of places where configs can be found. Hydra searches through this list when trying to load configs.

Plugin discovery happens before config discovery. The `searchpath_config.py` is discovered first, and the `JeanZaySearchPathPlugin` is loaded from that file. Loading that file [causes modification of the searchpath](https://github.com/zaccharieramzi/jz-hydra-submitit-launcher/blob/00717f0367e61c52bba76f915811bfde8af22b75/hydra_plugins/jz_hydra_submitit_launcher_plugin/searchpath_config.py#L14), which results in the package `pkg://jz_hydra_submitit_launcher` being added to Hydra's search path. This means the configs inside the `jz_hydra_submitit_launcher` are now discoverable by Hydra.

**Comment by Jasha10** [comment]
> In any case I think it would be better to have it all in the same directory, if you don't mind changing it. If you do, don't forget to change the path to the script: https://github.com/Jasha10/jz-hydra-submitit-launcher/blob/use_namespace_package/setup.py#L34

Done in https://github.com/zaccharieramzi/jz-hydra-submitit-launcher/pull/1/commits/2ec13ab25f8d2be13778fd27dc88db3e4aa28f98.

FYI It is usually possible for you to modify PRs on your repository by pushing commits directly to the git branch that the PR is based upon (see [this link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork)).

**Comment by zaccharieramzi** [comment]
Thanks so much @Jasha10 .
Sorry to have asked you to do the directory change, I indeed did not know I could push to your branch...
This LGTM, so I am merging it once the relatively simple test has passed.

**Review by zaccharieramzi — APPROVED** [review]

**Pull request merged**
